### ISSUE TITLE
RooFit not added in CMake options

### ISSUE THREAD

**Issue by adamdddave** [ttekampe/SciFiTestbeamAndSimulation#1]
Seems like the cmake variable $ROOFIT_LIBRARIES is not being correctly assigned and is not found for Calibration compilation.

```
[ 55%] Building CXX object src/CMakeFiles/Calibration.dir/Calibration.cpp.o
/SciFiTestbeamAndSimulation/src/Calibration.cpp:16:10: fatal error: 'RooRealVar.h' file not found
#include "RooRealVar.h"
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/Calibration.dir/Calibration.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/Calibration.dir/all] Error 2

```

Probably a problem with the CMake file. Looking into it.

**Comment by ttekampe** [comment]
I cannot reproduce this. I just checked out the repo and compiled on my laptop (arch linux).
The only bug that I found was a missing `#include <numeric>` which I just fixed.

Maybe having a look to
`SciFiTestbeamAndSimulation/cmake/FindROOT.cmake
`
can help
